/*
 * File: app/view/Resource.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FileManager.view.Resource', {
    extend: 'Ext.container.Container',

    cls: 'resource',
    height: 100,
    width: 100,
    layout: {
        align: 'center',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'image',
                    flex: 1,
                    height: 100,
                    itemId: 'resourceImg',
                    width: 100,
                    src: 'static/file.png'
                },
                {
                    xtype: 'label',
                    itemId: 'resourceName',
                    text: 'My Label'
                }
            ]
        });

        me.callParent(arguments);
    }

});